name: Text & Publish

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test

    steps:
      - uses: actions/checkout@master
      - run: npm i
      - run: npm test

  publish:
    runs-on: ubuntu-latest
    name: Publish

    needs: [test]

    if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}

    steps:
      - uses: actions/checkout@master
      - run: npm i -g wrangler
      - run: npm i
      - run: npm run build

      - run: wrangler publish -c ./wrangler.toml
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}

      - name: Log to LogSnag
        uses: jsmrcaga/action-logsnag@v0.0.2
        with:
          token: ${{ secrets.LOGSNAG_TOKEN }}
          project: urls
          channel: publish
          event: Published a new version (${{ github.run_number }})!
          description: Published a new version to workers
          icon: 🌍
          notify: true
